[package]
name = "rain-lang"
edition = "2021"
authors = ["hello@nikee.dev <Nikita Goncarenko/nikeedev>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2.0.4"
serde = { version = "1.0.197", features = ["derive"] }
toml = "0.8.12"
