#### https://github.com/nikeedev/storm
#### How the storm project and droplet manager would look like


[project]
name = "rain-lang"
author = ["Nikita Goncarenko"]
version = "0.1.3a"
description = "Rain programming language compiler source code"
raindrop = 1#st
out = "exe"

[droplets]
test = "0.1.0"
another_test = "0.1.0"
